version: "3.8"
services:
  react-client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-dc
    ports:
      - 3000:3000
    volumes:
      - "./client:/usr/app"
      - "/usr/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
  express-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: express-dc
    ports:
      - 5000:5000
    volumes:
      - "./server:/usr/app"
      - "/usr/app/node_modules"
    environment:
      - CHOKIDAR_USEPOLLING=true
